Kernel360/KDEV5-MY-WORK-FE

- src/components/CustomTable/CustomTable.jsx
- src/layouts/MainLayout.styles.js
- CustomTable 컴포넌트에 진행도 (Progress Bar) 타입을 추가하고
- 가로/세로 스크롤이 깔끔하게 동작하도록 레이아웃 전반 수정
- 'progress' 타입 컬럼 추가 및 LinearProgress UI 구현
- Paper -> Box 구조로 overflow 조절
- 'height', 'overflow', 'flexGrow' 등 레이아웃 스타일링 개선
- 불필요한 외부 스크롤 제거
- 브라우저 화면 축소/확대, 아이템 100개 이상 입력
- 진행도 0%, 50%, 100% 테스트 완료
- `- #9 ` - CustomTable 공통 컴포넌트 개발 및 기능 고도화
- [MUI Table Layout Best Practices] (http://mui.com/material-ui/react-table/)
> feat: CustomTable에 progress 타입 추가 및 스크롤 레이아웃 수정(#9)

- src/api/api.js
- src/features/auth/authSlice.js
- src/features/auth/pages/LoginPage.jsx
- src/store/store.js
* Redux Toolkit을 이용해 인증 상태 관리(`authSlice`)와 로그인 페이지(`LoginPage`)를 구현했습니다.
* 로그인, 토큰 재발급, 로그아웃 기능을 비동기 Thunk로 처리하고, 로그인 성공 시 역할에 따라 프로젝트 페이지로 리다이렉트하도록 설정했습니다.
* **`authSlice` 추가**
* `login`, `reissueToken`, `logout` 비동기 Thunk 구현
* 초기 상태를 `localStorage`에서 복원하도록 설정
* 로그인 성공 시 `accessToken`·`expiresAt`·`user` 정보를 `localStorage`에 저장
* 토큰 재발급 시 `localStorage` 업데이트, 로그아웃 시 모든 인증 정보 제거
* `clearAuthState` 리듀서로 Redux 상태와 `localStorage` 초기화 기능 구현
* **`LoginPage` 컴포넌트 구현**
* 이메일/비밀번호 입력 폼과 제출 핸들러 추가
* `dispatch(login(form))` 호출 후 성공 시 `memberRole`을 확인하여:
* `ROLE_SYSTEM_ADMIN`인 경우 `/projects`로 즉시 이동
* 그 외의 사용자는 `/api/projects?memberId={memberId}&page=1&pageSize=1` 호출 후,
* 참여 중인 프로젝트가 있으면 첫 번째 프로젝트 상세로 이동
* 프로젝트가 없으면 `clearAuthState()` 후 Snackbar 경고 메시지 출력
* 로그인 실패 또는 프로젝트 조회 오류 시 Snackbar로 사용자에게 알림 표시 …
> feat: 인증 상태 관리 및 로그인 페이지 구현(#36)

- constants/navItems.js
- src/features/auth/authSlice.js
- src/layouts/Sidebar.jsx
- src/utils/roleUtils.js
* Redux `auth` 상태로부터 로그인된 사용자의 `memberName`과 `memberRole`을 가져와 사이드바 상단에 표시하고, 각 메뉴 항목에 허용된 권한(`roles`)을 정의하여 로그인된 사용자의 권한에 맞게 사이드바 메뉴를 필터링하여 렌더링하도록 구현했습니다.
---
* **Redux `auth` 상태 참조**
* 사이드바 컴포넌트에서 `state.auth.user.name`(`memberName`)과 `state.auth.user.role`(`memberRole`)을 가져와 프로필 영역에 노출
* **`navItems` 데이터 구조 확장**
* 기존 `{ text, icon, path }` 구조에 각 메뉴별 허용 권한(`roles: ['SYSTEM_ADMIN', 'DEV_ADMIN', ...]`) 속성 추가
* **권한 기반 메뉴 렌더링 로직**
* 로그인된 사용자의 `memberRole`을 기준으로, 해당 권한이 포함된 메뉴 항목만 필터링하여 렌더링
* 필터링된 결과로 `NavList`에 노출될 메뉴 리스트 생성
* **권한 검사 및 예외 처리**
* 사용자의 권한(`memberRole`)이 없거나 예상치 못한 값일 경우 `window.alert`로 경고 메시지를 띄우고, Redux `clearAuthState()` 호출 후 `/login`으로 리다이렉트
* **상태 복원 및 로그아웃 처리**
* 페이지 새로고침 시 로컬 스토리지에 저장된 `accessToken`을 통해 Redux `auth` 상태를 복원하여 권한 정보가 유지되도록 구현
* 로그아웃 시 Redux 상태 및 로컬 …
> feat: 권한 기반 사이드바 메뉴 렌더링 및 사용자 정보 노출(#45)

- constants/navItems.js
- src/components/common/customTable/CustomTable.jsx
- src/components/common/sectionTable/SectionTable.jsx
- src/components/layouts/tabsWithContent/TabsWithContent.jsx
- src/features/auth/authSlice.js
- src/features/project/components/PostTable.jsx
- src/features/project/components/ProjectManagement.jsx
- src/features/project/components/ProjectTable.jsx
- src/features/project/pages/ProjectDetailPage.jsx
- src/layouts/Sidebar.jsx
- src/utils/roleUtils.js
* `ProjectDetailPage` 컴포넌트의 전체 레이아웃을 고정하고, 내부 탭 콘텐츠 및 자식 컴포넌트의 스크롤 동작을 개선했습니다.
* 이로써 사이드 마진(`mx: 3`)을 적용해도 부모 폭이 깨지지 않고, 필요한 영역에서만 스크롤이 발생하도록 변경하였습니다.
---
* **최상위 컨테이너 레이아웃 고정**
* `height: 100vh`, `display: flex`, `flexDirection: column` 설정하여 페이지 전체 레이아웃이 일정하게 유지되도록 함
* `width: 100%`, `maxWidth: 100%`, `boxSizing: border-box` 추가해 부모 폭이 절대로 늘어나지 않도록 조정
* **탭 영역 래퍼(`Box`) 수정**
* `mx: 3` 환경에서도 부모 폭을 유지하기 위해 `flex: 1`, `minWidth: 0` 속성을 적용
* `overflowX: hidden` → `overflowX: auto` 또는 적절히 분리하여, 내부 콘텐츠 가로 넘침 시 스크롤만 동작
* **`TabsWithContent` 및 내부 콘텐츠 박스 수정**
* `Paper`와 내부 `<Box>`에 `width: 100%`, `maxWidth: 100%`, `boxSizing: border-box` 적용
* `overflowX: auto`, `overflowY: auto`를 사용해 가로·세로 스크롤 구간을 분리 (탭바 고정, 콘텐츠 영역만 스크롤)
* **내부 컴포넌트(`ProjectManagement`, `PostTable` 등) 업데이트**
* 각 컴포넌트 최상위에 `width: …
> [feat]ProjectDetailPage 레이아웃 및 스크롤 개선(#34)

- src/features/company/companySlice.js
- src/features/company/components/DevCompanyTable.jsx
- src/features/company/pages/DevCompanyDetailPage.jsx
- src/routes/MainRoutes.jsx
- 개발사 상세 페이지 상단 개발
- 개발사 단건 상세 페이지 상단 부분 개발
- 개발사 단건 상세 조회 API 호출
- #77
> [feat] 개발사 상세 페이지 상단 개발

- constants/navItems.js
- src/layouts/Sidebar.jsx
* 사이드바 메뉴 렌더링 구조를 리팩토링하여 확장성과 일관성을 개선했습니다.
* children 유무에 따라 섹션 타이틀(`Typography`) 노출 방식 분리
* 토글(Collapse) 제거 후 항상 펼쳐진 형태로 하위 메뉴 노출
* ROLE\_USER 분기 제거 → 전체 공통 렌더링 구조 통합
* navItems 구조 기반으로 유연하게 children 기반 렌더링
* 전체 코드 가독성 및 유지보수성 개선
* 로컬에서 권한별 계정으로 로그인하여 전체 사이드바 메뉴 렌더링 확인
* navItems 구조에 맞게 정상 렌더링 및 클릭 시 페이지 이동 확인
* children 유무에 따른 UI 정상 동작 확인
* #190 
* 없음
> [refactor]사이드바 메뉴 렌더링 구조 리팩토링(#190)

- src/features/dashboard/pages/DashboardPage.jsx
- src/routes/MainRoutes.jsx
* 대시보드 페이지의 전체 레이아웃 구조 및 데이터 표시 로직의 기본 틀을 작업했습니다.
* 이후 상세 기능 구현을 위한 뼈대 작업입니다.
* PageWrapper 및 PageHeader 적용
* 대시보드 프로젝트 현황(전체, 진행중, 만료) UI 레이아웃 구성
* 마감임박 / 게시글 많은 프로젝트 섹션 레이아웃 구성
* 하드코딩 데이터를 기반으로 전체 흐름 설계
* 하드코딩 데이터를 기반으로 정상 렌더링 확인
* 각 섹션 별 데이터 및 페이지네이션 UI 정상 출력 확인
* `- #대시보드 신규 페이지 개발`
* 없음
> feat: 대시보드 페이지 레이아웃 기본 틀 생성(#193)

- .env
- .env.development
- .env.production
- src/api/api.js
- Vite 개발/운영 환경 분리 및 API 주소 설정
- `.env.development` / `.env.production` 파일 분리 및 API 주소 설정
- Axios 인스턴스에 `import.meta.env.VITE_API_BASE_URL` 적용
- #206 
- [Vite 공식 문서 - 환경 변수](https://vitejs.dev/guide/env-and-mode.html)
> [feat]Vite 개발/운영 환경 분리 및 API 주소 설정(#206)

- src/components/common/customButton/CustomButton.jsx
- src/components/common/customTable/CustomTable.jsx
* 테이블 내 수정/삭제 버튼이 `ROLE_SYSTEM_ADMIN` 권한을 가진 사용자에게만 노출되도록 조건부 렌더링을 적용했습니다.
* CustomButton 컴포넌트에 `ghost-danger` 스타일을 추가하여 삭제 버튼에 적용했습니다.
* 기존 MUI Button을 모두 CustomButton으로 교체하였습니다.
---
* CustomButton에 `ghost-danger` 스타일 추가 (빨간 테두리)
* ghost 버튼의 테두리 색상을 글자 색상과 동일하게 변경
* CustomTable 내 수정/삭제 버튼을 CustomButton으로 교체
* Redux에서 사용자 권한(role) 값을 조회해 `ROLE_SYSTEM_ADMIN`일 때만 수정/삭제 버튼 노출되도록 조건부 렌더링 적용
---
---
* `ROLE_SYSTEM_ADMIN` 사용자로 로그인하여 수정/삭제 버튼이 정상 노출되는지 확인
* 다른 권한(`ROLE_MANAGER`, `ROLE_USER`)에서는 버튼이 보이지 않는 것을 확인
* 삭제 및 수정 동작 정상 작동 확인
* 버튼 hover 및 disabled 스타일 문제 없이 작동
---
* #204 
---
* [[MUI Button customization](https://mui.com/material-ui/customization/theme-components/#component-customization)](https://mui.com/material-ui/customization/theme-components/#component-customization)
* [[Redux …
> [feat]테이블 행 수정/삭제 버튼 ROLE_SYSTEM_ADMIN 권한일 때만 노출되도록 변경(#204)

- src/components/common/sectionTable/SectionTable.jsx
- src/features/project/post/components/PostTable.jsx
- 프로젝트 상세 새글작성 버튼,프로젝트 스탭 리디자인
- 프로젝트 상세 페이지 프로젝트 스탭 및 생성 버튼 리디자인.
#216
> [feat] 프로젝트 상세 새글작성 버튼,프로젝트 스탭 리디자인 #216

- src/api/member.js
- src/features/company/pages/CompanyDetailPage.jsx
- 회사 상세 정보에 직원리스트 호출 API 변경 #220
- 회사상세 페이지 직원 리스트 API 변경
- <img width="565" alt="image" src="https://github.com/user-attachments/assets/e61d23d1-31f5-4709-8af1-6259e314f2ea" />
#220
> 회사 상세 정보에 직원리스트 호출 API 변경 #220

- src/api/dashboard.js
- src/features/dashboard/DashboardSlice.js
- src/features/dashboard/pages/DashboardPage.jsx
- src/store/store.js
* 대시보드 페이지에 백엔드 API를 연동하여 실제 데이터를 기반으로 프로젝트 요약 및 마감 임박 프로젝트 정보를 표시하도록 구현했습니다.
---
* `api/dashboard.js`에 요약 정보 및 마감 프로젝트 API 함수 추가
* `dashboardSlice.js` 생성하여 Redux 상태 관리 로직 구성
* `DashboardPage.jsx`에 대시보드 API 연동 및 시각화 구현
* 요약 정보: 전체, 진행중, 완료
* 마감 임박 프로젝트(D-5 이하) 목록 및 D-day 뱃지 스타일 추가
---
---
* 로컬 서버에서 마감 임박 프로젝트 및 요약 정보 정상 출력 확인
* 페이지 이동 시 해당 페이지 데이터 정상 호출 확인됨
---
* #223 
---
* 없음
> feat: 대시보드 페이지에서 프로젝트 요약 및 마감 임박 프로젝트 목록 표시 기능 구현 (#223)

- src/features/auth/pages/LoginPage.jsx
- src/routes/MainRoutes.jsx
* 로그인 성공 시 권한과 무관하게 대시보드(`/dashboard`)로 이동하도록 리디렉션 경로를 수정했습니다.
---
* 기존에 `ROLE_USER`일 경우만 별도 프로젝트 조회 후 리디렉션하던 로직 제거
* 로그인 성공 시 `/dashboard`로 일괄 이동하도록 처리
* `fetchMemberProjects` 호출 및 관련 분기 로직 삭제
* `/projects`, `/no-projects` 관련 이동 경로 제거
---
---
* 로컬에서 로그인 시 `/dashboard`로 정상 이동되는지 직접 테스트 완료
* 로그인 실패 시에는 에러 메시지 정상 출력됨 확인
---
* #225 
---
* 없음
> [feat] 로그인 성공 시 대시보드로 이동하도록 리디렉션 경로 수정(#225)

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- GitHub 이슈 템플릿 제목 포맷을 커밋 메시지 및 PR 스타일과 일관되도록 소문자(`lowercase`)로 변경했습니다.
- `.github/ISSUE_TEMPLATE/feature-request.md`  
- 제목 포맷 `[Feature]` → `[feat]`
- `.github/ISSUE_TEMPLATE/bug-report.md`  
- 제목 포맷 `[Bug]` → `[bug]`
- GitHub에서 두 템플릿 모두 수정 후 이슈 생성 시 정상 출력 확인
- #197 
- 없음
> [chore] 이슈 템플릿 제목 포맷 수정(#197)

- src/features/project/home/components/ProjectBasicInfoSectionContent.jsx
- src/features/project/home/pages/ProjectLayout.jsx
프로젝트 상태값 이름변경 및상세페이지에  결제금액 필드 노출#258
- 프로젝트 상태값 이름변경 
- 상세페이지에  결제금액 필드 노출( 결제, 진행중 , 검수 ,완료)
#258
> feat: 프로젝트 상태값 이름변경 및상세페이지에  결제금액 필드 노출#258

- src/features/notifications/components/NotificationsDrawer.jsx
- src/features/notifications/notificationSlice.js
- src/layouts/MainLayout.jsx
- src/layouts/Sidebar.jsx
- src/store/store.js
- src/utils/dateUtils.js
- 알림 페이지 생성
- 알림 아이콘 추가 ( 사이드바 최상단에 위치 )
- 알림 페이지 생성 ( 기존 post 와 디자인 동일 )
- 알림 날짜에 대한 공통 js 추가 ( 오늘 날짜면 X시간전, 오늘이 아니면 X일전, 1주일이 넘으면 yyyy-MM-dd 형식노출)
- mock 데이터로 화면 확인.
#260
> feat: 알림 페이지 생성 #260

- src/features/project/home/pages/ProjectFormPage.jsx
- 프로젝트 생성 버튼 위치 변경 #279
- 버튼 위치 변경.
#279
> chore: 프로젝트 생성 버튼 위치 변경 #279

- src/features/project/home/components/ProjectBasicInfoSectionContent.jsx
- src/features/project/home/hooks/useProjectDetailSections.jsx
- src/features/project/home/pages/ProjectDetailPage.jsx
-프로젝트 상세 상태,가격 필드 추가 #309
- 프로젝트 상세페이지 수정폼 일때 상태와 가격 필드 추가.
화면테스트
#309
> fix: 프로젝트 상세 상태,가격 필드 추가 #309

- src/features/project/post/components/CreatePostDrawer.jsx
- src/features/project/post/components/PostDetailDrawer.jsx
- src/features/project/post/postSlice.js
게시글 첨부 기능을 이미지 전용에서 범용 파일 첨부로 확장하고, 공통 CustomButton 컴포넌트 적용으로 UI 일관성 개선
- 이미지 전용 파일 타입 검증 로직을 범용 파일 업로드로 확장
- 위험 파일 확장자 블랙리스트 적용 (.exe, .bat, .cmd 등 차단)
- 파일 타입별 아이콘 표시 로직 추가 (PDF, DOC, ZIP 등 구분)
- 업로드 허용 파일 안내 문구 수정
- 첨부파일 표시 방식을 큰 이미지(300px)에서 작은 파일 리스트(40px)로 변경
- 한 줄에 하나씩 파일 정보 표시하는 컴포넌트 구현
- 파일 타입별 아이콘 및 파일명, 크기 정보 표시
- 다운로드 버튼 추가 및 강제 다운로드 기능 구현
- 이미지 파일의 경우 미리보기 기능 유지
- 게시글 조회 시 첨부파일 상태 초기화 문제 해결 (이전 게시글 데이터 잔존 방지)
- CustomButton 컴포넌트 적용으로 UI 일관성 확보
- ✅ PDF, DOC, XLS, ZIP 등 다양한 파일 타입 업로드 성공
- ✅ 위험 파일(.exe, .bat) 업로드 차단 확인
- ✅ 파일 다운로드 기능 정상 작동 (강제 다운로드)
- ✅ 이미지 파일 미리보기 기능 유지
- ✅ 게시글 A → 게시글 B 조회 시 첨부파일 상태 초기화 확인
- ✅ 파일 리스트 형태로 깔끔한 표시
- ✅ 파일 타입별 구분되는 아이콘 표시
- ✅ CustomButton 적용으로 일관된 버튼 디자인
- ✅ 한 줄에 하나씩 파일 정보 표시로 가독성 향상
- #316
> [feat] 게시글 작성에 이미지 첨부를 파일 첨부로 확장

- src/features/notifications/components/NotificationsDrawer.jsx
- src/features/project/approval/pages/ProjectApprovalsPage.jsx
* 동일한 프로젝트 결재 페이지(`/approvals`)에 이미 머물러 있는 상태에서 알림을 클릭해도 drawer가 열리지 않던 문제를 해결
---
* 알림 클릭 시 `navigate`에 `state`를 통해 `openTargetId` 전달
* `ProjectApprovalsPage`에서 `useLocation().state`로 해당 ID를 감지하고 drawer 오픈
* 기존 쿼리 기반 접근 대신 React Router의 state 기반 방식 적용
---
---
* `/projects/1/approvals` 페이지에 있는 상태에서 알림 클릭 시 해당 체크리스트 drawer가 정상적으로 열림
* `/projects/2/approvals` 등 다른 페이지 이동 시에도 정상 동작
* state를 활용한 이동이라 브라우저 새로고침 시에는 영향 없음 (의도된 동작)
---
* #319 
* #304 
---
* [[React Router - Navigate with state](https://reactrouter.com/en/main/hooks/use-navigate)](https://reactrouter.com/en/main/hooks/use-navigate)
* [[React Router - useLocation](https://reactrouter.com/en/main/hooks/use-location)](https://reactrouter.com/en/main/hooks/use-location)
> [fix] 동일 페이지에서 알림 클릭 시 drawer가 열리지 않는 문제 수정 (#319)

- src/api/notification.js
- src/features/notifications/notificationSlice.js
- src/hooks/useNotificationPolling.js
- src/layouts/MainLayout.jsx
- src/layouts/Sidebar.jsx
- 알림의 미읽음 개수를 백엔드에서 조회하여 Redux로 관리하고, 사이드바 알림 아이콘에 뱃지로 표시되도록 구현했습니다.
- 기존 알림 폴링 로직을 리팩터링하여 미읽음 개수만 주기적으로 조회하도록 개선했습니다.
- 알림 미읽음 개수 조회 API 함수 추가 (`getUnreadNotificationCount`)
- Redux Thunk (`fetchUnreadNotificationCount`) 및 리듀서 로직 구현
- 사이드바 알림 아이콘에 뱃지 표시 추가 (`<Badge>`)
- `useNotificationPolling` 내부에서 `refreshNotifications` → `fetchUnreadNotificationCount`로 변경
- 로컬 환경에서 로그인 후 알림 미읽음 수가 3분마다 갱신되는지 확인
- 알림 drawer를 열면 폴링이 중단되고, 닫으면 재시작되는지 확인
- unread count 값에 따라 뱃지가 자연스럽게 사라졌다 나타나는지 확인
- #326
- 없음
> [feat] 알림 미읽음 개수 조회 및 사이드바 뱃지 표시 기능 추가 (#326)

- src/api/post.js
- src/features/project/post/components/CreatePostDrawer.jsx
- src/features/project/post/postSlice.js
백엔드 API 명세 변경에 따른 첨부파일 일괄 활성화 요청/응답 형식 수정
첨부파일 일괄 활성화 API 요청 바디에 postAttachmentIds 필드 추가
API 함수 파라미터 타입 수정: { postId } → { postId, postAttachmentIds }
Redux async thunk 액션 파라미터 업데이트
CreatePostDrawer 컴포넌트에서 성공한 파일들의 ID 배열 생성 후 API 호출
API 요청/응답 확인
- ✅ 요청 바디에 postId, postAttachmentIds, active 필드 정상 전송
- ✅ 응답에서 data.postAttachments 배열 구조 정상 수신
- ✅ 파일 3개 업로드 후 일괄 활성화 성공
- ✅ 게시글 생성 + 파일 첨부 + 일괄 활성화 전체 플로우 정상 작동
- #332 
변경된 API 명세
- https://github.com/Kernel360/KDEV5-MY-WORK-BE/pull/300
> feat : 첨부파일 활성화 API 명세 변경 부분 적용 (#332)

- src/features/company/pages/CompanyFormPage.jsx
- feat: 회사 생성시 중복 사업자번호 알럿 노출
회사 생성시 중복 사업자번호 알럿 노출
오류코드 compnay 6 번에 대해서 전달받은 message를 그대로 노출 현재 문구 ( 사업자 번호를 가진 회사가 존재합니다.)
화면에 공통 컴포넌트 알럿 노출 ( 사업자 번호를 가진 회사가 존재합니다.)
#337
> feat: 회사 생성시 중복 사업자번호 알럿 노출 #337

- src/features/notifications/components/NotificationContentBox.jsx
- src/features/notifications/components/NotificationsDrawer.jsx
- 읽지않은 알림 디자인 변경 
- 읽지 않은 알림 표시 점을 연빨강색(#ff6b6b)으로 변경
- 맥박 애니메이션 속도를 1.5배 빠르게 조정 (2초 → 1.33초)
- 동그라미 크기 변화 애니메이션 추가 (80% ↔ 100% 스케일링)
- 읽지 않은 알림 박스 테두리를 부드럽게 개선 (2px 진한색 → 1px 연한색)
- 순수 CSS 키프레임 애니메이션으로 맥박 효과 구현
- 읽지 않은 알림 표시: 연빨강 점이 1.33초 주기로 80%↔100% 크기 변화하며 맥박 애니메이션 정상 동작
- #346
> feat : 읽지않은 알림 디자인 변경 (#346)

- src/features/project/post/components/PostDetailDrawer.jsx
- src/features/project/post/pages/ProjectPostsPage.jsx
-  post삭제 생성시 페이지 이동및 데이터 갱신 추가 #348
- post  생성 , 삭제 시 페이지 데이터 갱신  되도록 추가.
화면 테스트
#348
> fix : post삭제 생성시 페이지 이동및 데이터 갱신 추가 #348

- src/features/notifications/components/NotificationsDrawer.jsx
- src/utils/notificationIconMap.js
- src/utils/notificationLabelMap.js
* 알림 메시지를 `targetType`과 `actionType`에 따라 조건부로 다르게 출력되도록 로직을 수정했습니다.
* 게시글(POST)의 상태 변경은 `"변경하였습니다"` 문구로, 그 외 알림은 `"남겼습니다"` 문구로 출력됩니다.
---
* 알림 메시지 조건 분기 로직 추가
* `targetType === "POST"` && `actionType !== "REVIEW"` → `변경하였습니다` 문구 출력
* 그 외는 기존 `"남겼습니다"` 문구 유지
* `getPostLabel`, `getChecklistLabel`을 메시지 종류에 따라 각각 적용
---
---
* 다양한 알림 mock 데이터를 기반으로 메시지 출력 확인
* `POST` 변경 알림은 `"상태를 [상태명]로 변경하였습니다"`로 출력됨
* `CHECKLIST`, `REVIEW` 등은 기존대로 `"남겼습니다"` 문구 유지됨
* 시각적으로 문제 없이 렌더링됨
---
* #350 
---
* 없음
> feat: 알림 메시지를 targetType과 actionType에 따라 분기 처리(#350)

- src/features/company/pages/CompanyFormPage.jsx
- company_id 로컬스토리지 저장 제거 및 업체등록 페이지 접속마다 새로 발급
- company_id 로컬스토리지 저장 제거
- 업체등록 페이지 접속마다 company_id 새로 발급
- #352
> feat : company_id 로컬스토리지 저장 제거 및 업체등록 페이지 접속마다 새로 발급

- src/features/project/post/components/CommentSection.jsx
- src/features/project/post/components/FileAttachmentViewer.jsx
- src/features/project/post/components/PostDetailDrawer.jsx
- src/features/project/post/reviewSlice.js
* 게시글 상세 보기에서 댓글이 많을 경우 "더보기" 버튼을 통해 페이징 처리되도록 기능을 추가했습니다.
* 댓글 조회 API 호출 시 페이지 번호 파라미터 추가
* Redux `reviewSlice`에 `hasMore` 필드 및 페이지 상태 추가
* 첫 페이지일 경우 덮어쓰기, 이후 페이지는 이어붙이도록 로직 변경
* `CommentSection` 컴포넌트에 "더보기" 버튼 렌더링 및 클릭 핸들러 추가
* 마지막 페이지일 경우 버튼이 사라지도록 처리
* 댓글이 20개 이상인 게시글에서 "더보기" 버튼을 클릭 시, 다음 댓글 10개가 이어서 렌더링됨
* 마지막 페이지(응답 개수 < 10) 도달 시 버튼이 자동으로 사라짐
* 댓글이 10개 이하인 경우 버튼이 처음부터 나타나지 않음
* 수동 테스트 완료 및 QA 확인
* #354 
* 없음
> [feat] 댓글 리스트에 “더보기” 버튼 추가 및 페이징 처리(#354)

- src/features/company/pages/CompanyPage.jsx
- src/features/member/components/MemberTable.jsx
- src/features/member/pages/MemberPage.jsx
* 회사, 프로젝트, 회원 목록 등의 리스트 영역에서 스크롤이 동작하지 않던 문제를 수정하고, 전체 영역에서 일관된 스크롤 동작을 적용하였습니다.
* Box 스타일의 `overflow: hidden` → `overflow: auto`로 변경
* 회사/프로젝트/회원 목록 스크롤 스타일 통일
* 리스트 길이를 늘려 하단 항목까지 정상적으로 노출되는지 확인
* 다양한 브라우저 및 뷰포트에서 스크롤 동작 확인
* 기존 레이아웃 깨짐 없이 정상 작동 확인
* 없음
* 없음
> [fix] 회사/프로젝트/회원 목록 스크롤 동작 개선 (#374)

- src/features/company/components/CompanyTable.jsx
- src/features/company/pages/CompanyPage.jsx
- src/features/member/components/MemberTable.jsx
- src/features/member/pages/MemberPage.jsx
* `companyType` 파라미터를 제거하여 전체 회사 목록을 조건 없이 조회할 수 있도록 프론트 로직을 개선
* `companyType: "DEV"` 고정 파라미터 제거
* 조회 요청 시 companyType이 선택되지 않으면 전체 회사 목록이 출력되도록 요청 param 수정
* 회사 페이지에서 `companyType` 파라미터 없이 전체 회사 리스트 정상 조회 확인
* 검색어 입력, 페이징 이동 등 기능 정상 작동 확인
* #376 
* 없음
> refactor: companyType 파라미터 제거로 전체 회사 목록 조회 가능하도록 수정(#376)

- src/features/project/home/pages/ProjectPage.jsx
- src/features/project/post/pages/CreatePostDrawer.jsx
- src/hooks/usePostForm.js
* 게시글 작성 Drawer를 닫아도 입력값과 업로드 상태가 초기화되지 않는 문제를 해결
* 
* 게시글 작성 후 닫고 다시 열었을 때 텍스트, 파일, 선택값 등이 모두 초기화됨을 확인
* 파일 첨부 후 닫은 뒤 재오픈 시 업로드 목록이 유지되지 않음 확인
* 없음
* 없음
> [fix] 게시글 닫기 시 입력값 초기화(clear)가 동작하지 않는 버그 수정(#383)

- src/features/project/home/components/ProjectBasicInfoSectionContent.jsx
- src/features/project/home/components/ProjectForm.jsx
- 프로젝트 금액 방어추가 
- 프로젝트 금액 7자리 이상 입력되지 않도록 수정
- 7자리 이상시 입력안되고  공통 알럿 나오게 설정. 
( 프로젝트 금액은 만원 단위 입니다. 100억을 넘을수 없습니다. 관리자에게 문의해주세요.)
- <img width="795" alt="image" src="https://github.com/user-attachments/assets/e907e9ba-51d7-458b-bb74-f2ba7137998b" />
#394
> feat: 프로젝트 금액 방어추가 #394

- src/features/project/home/components/ProjectBasicInfoSectionContent.jsx
* 프로젝트 금액 입력란에 '만원' 단위를 표시해 사용자 편의성 향상
* `TextField`에 `InputAdornment`를 사용해 '만원' 단위 추가
* 입력 후 오른쪽에 '만원' 단위 정상 표시됨
* 숫자 입력 및 에러 메시지도 기존과 동일하게 동작함
* 없음
* [[MUI InputAdornment 공식 문서](https://mui.com/material-ui/api/input-adornment/)](https://mui.com/material-ui/api/input-adornment/)
> [feat] 프로젝트 금액 입력란에 '만원' 단위 표시 추가(#394)

- src/components/common/customTable/CustomTable.jsx
* 프로젝트 목록 테이블에서 데이터가 없을 때 페이지네이션이 표시되는 문제를 해결하고, 사용자에게 안내 문구를 표시하도록 수정했습니다.
---
* `rows.length === 0`인 경우 `<Pagination />` 숨김 처리
* `<TableBody>` 내부에서 "등록된 데이터가 없습니다." 메시지를 `<TableRow>`와 `<TableCell>`로 안전하게 렌더링
* 메시지를 가로·세로 모두 중앙 정렬되도록 스타일 적용
* hydration 에러 방지를 위해 `<tr>`가 `<div>` 밖에 렌더링되지 않도록 구조 정비
---
---
* 실제 프로젝트 데이터가 없는 상태에서 "등록된 데이터가 없습니다." 메시지가 올바르게 표시됨
* 데이터가 있을 경우 페이지네이션 및 테이블 렌더링 정상 작동 확인
* DevTools에서 hydration 관련 경고 메시지 없음 확인
---
* #397 
---
* 없음
> [fix] 데이터가 없을 때 페이지네이션 숨기고 안내 메시지 표시(#397)

- src/features/project/home/components/CompanyMemberList.jsx
- src/features/project/home/components/CompanyMemberSelector.jsx
* 구성원 카드 UI를 정리하고, 매니저 임명 기능을 `메뉴 아이템(Menu)`으로 분리하여 UX를 개선
* 구성원 카드 레이아웃 정리 (Chip 위치 및 정렬 개선)
* 역할별 색상 Chip 스타일링 추가
* `매니저 임명` 기능을 context menu (`MoreVertIcon` 메뉴 버튼)로 분리
* `MenuItem`에 아이콘(`PersonAddAltRounded`, `DeleteRounded`) 추가로 직관성 향상
* 역할 및 매니저 여부에 따라 메뉴 옵션 분기 처리
* 관리자/일반 사용자의 다양한 조합으로 역할에 따른 메뉴 노출 테스트 완료
* 매니저 임명 → 카드 UI에 "매니저" Chip 즉시 반영되는지 확인
* 구성원 삭제 → 카드가 정상적으로 제거됨을 확인
* #402
* 없음
필요하면 더 간단한 버전이나 영문도 제공할게요!
> [refactor] 구성원 카드 UI 개선 및 매니저 임명 기능을 메뉴로 분리(#402)

- package-lock.json
- package.json
- src/features/project/home/components/ProjectStepManager/ProjectStepManager.jsx
- src/features/project/home/components/ProjectStepManager/StepCard.jsx
- src/features/project/home/hooks/useProjectDetailSections.jsx
- src/features/project/home/hooks/useProjectForm.js
- src/features/project/home/pages/ProjectDetailPage.jsx
* 프로젝트 단계 관리와 관련된 로직을 개선하고, 상태 관리를 `useProjectForm` 훅을 사용하여 분리
* 신규 단계와 기존 단계 처리 로직을 개선하고, 단계 제목에 상태를 표시하는 UI 변경이 포함
* **단계 제목에 상태 표시**:
* 'Edited'와 'New' 상태를 각각 Chip으로 표시하여 사용자에게 명확히 구분
* 'Edited'는 경고 색상, 'New'는 정보 색상으로 표시
* **단계 생성 및 업데이트 처리 로직 개선**:
* 신규 단계는 `createProjectStages`를 호출하여 추가하고, 기존 단계는 `updateProjectStages`로 업데이트 처리
* `orderedSteps` 배열에서 신규 단계와 기존 단계를 분리하여 처리
* **상태 관리 리팩토링**:
* `ProjectDetailPage`에서 단계 상태 관리 로직을 `useProjectForm` 훅으로 분리하여 코드 재사용성 및 유지보수성 향상
* **UUID 패키지 설치**:
* 고유한 단계 ID 생성을 위해 `uuid` 패키지 설치
* UI에서 단계 제목 옆에 'Edited'와 'New' 상태가 정상적으로 표시됨
* 신규 단계와 기존 단계의 생성 및 업데이트 로직이 의도대로 작동함
* `useProjectForm` 훅을 통해 상태 관리가 잘 분리되었으며, 관련 기능이 정상적으로 작동
* `- #417
* 없음
> [feat] 프로젝트 단계 상태 관리 개선 및 UI 업데이트(#417)

- src/features/project/home/components/CompanyMemberSelector.jsx
- src/features/project/home/components/ProjectForm.jsx
- src/features/project/home/pages/ProjectFormPage.jsx
- 프로젝트 직원 매니저 할당 버그 수정
-프로젝트 직원 추가시 누락 필드 를 통해 매니저 할당이 가능.
-매니저 할당 될 수 없도록  필드 추가 role , manager
화면 테스트 정상 케이스 확인.
#431
> fix : 프로젝트 직원 매니저 할당 버그 수정

- src/components/common/customTable/CustomTable.jsx
- src/features/logs/components/LogsTable.jsx
- 회사 수정 페이지 이미지 업로드 기능 개선 및 로그 페이지 UI 정리 작업을 완료했습니다.
- 코드 품질 향상을 위해 console.log 제거 및 상세한 주석 추가 작업을 진행했습니다.
- 이미지 선택 시 presigned URL 발급 후 S3 직접 업로드 구현
- 수정 모드에서 회사 ID를 바로 사용하여 업로드 로직 최적화
- 기존 이미지 교체 시 서버 삭제 → 새 이미지 업로드 순서로 처리
- 미리보기 기능 및 업로드 상태 표시 개선
- 모든 console.log 제거 (프로덕션 환경 대응)
- JSDoc 스타일 상세 주석 추가
- 함수별 목적, 매개변수, 반환값 명시
- 비즈니스 로직 처리 흐름 설명 추가
- CustomTable 컴포넌트에 `hideActionsColumn` prop 추가
- 로그 페이지에서 불필요한 관리 컬럼 완전 제거
- 테이블 레이아웃 최적화
- ✅ 이미지 선택 시 즉시 미리보기 표시 확인
- ✅ presigned URL 발급 → S3 업로드 → 폼 상태 업데이트 흐름 정상 동작
- ✅ 기존 이미지 교체 시 서버 삭제 후 새 이미지 업로드 정상 처리
- ✅ 에러 발생 시 폼 상태 초기화 정상 동작
- ✅ 관리 컬럼 완전 제거 확인
- ✅ 다른 페이지의 CustomTable 기능 정상 동작 확인
- ✅ 필터링 및 페이지네이션 기능 정상 동작
- ✅ 모든 console.log 제거 완료
- ✅ 브라우저 콘솔에 개발용 로그 출력 없음 확인
- ✅ JSDoc 주석이 IDE에서 정상 표시되는지 확인
- 관련 이슈번호가 있다면 여기에 추가해주세요.
- 예: `#426` - 회사 수정 …
> bug : 로그 페이지 사용하지 않는 컬럼(관리 컬럼) 삭제

- package-lock.json
- package.json
- src/features/project/home/components/CompanyMemberList.jsx
- src/features/project/home/components/CompanyMemberSectionContent.jsx
- src/features/project/home/components/CompanyMemberSelector.jsx
- src/features/project/home/hooks/useProjectDetailSections.jsx
- src/features/project/home/hooks/useProjectForm.js
- src/features/project/home/pages/ProjectDetailPage.jsx
- src/features/project/slices/projectMemberSlice.js
- src/hooks/usePostForm.js
* 회사(개발사/고객사) 직원 관리 기능을 리팩토링하여
초기 할당 상태를 추적하고, 선택된 직원 목록의 변경 여부를 감지·리셋할 수 있는 로직을 추가했습니다.
* `assigned` 상태의 초기값을 별도 변수(`initialAssigned`)로 저장
* 사용자가 직원 선택·해제 시 변경 여부(`isEdited`)를 자동으로 감지하도록 로직 구현
* “초기 상태로 리셋” 기능 추가: 변경 전 상태로 되돌리는 핸들러 제공
* Redux slice 및 컴포넌트 수준에서 선택된 직원 상태 관리 방식을 일원화
* 관련 유틸 및 훅(`useCompanyMemberSectionContent`) 내부 로직 클린업 및 주석 보강
* 직원 목록에서 여러 건 선택 → `isEdited=true` 확인
* 리셋 클릭 → 선택 목록이 초기값으로 복원되고, `isEdited=false` 확인
* 추가·삭제 반복 후에도 상태 안정성 유지
* 브라우저 콘솔 및 네트워크 패널 이상 없음
* #417 
없음
> [refactor] 회사 직원 관리 기능 개선 – 초기 할당 상태 추적 및 변경 감지·리셋 로직 추가 (#417)

- src/features/project/home/components/ProjectStepManager/ProjectStepManager.jsx
- src/features/project/home/hooks/useProjectForm.js
* 프로젝트 저장 API 요청 시 `deleted` 필드 누락으로 발생하던 null 예외를 방지하도록 payload에 기본값 추가
* 단계 편집 후 `isEdit` 플래그가 유지되도록 로직 개선
* 매니저 토글 변경을 초기 스냅샷(`initialDevAssigned`/`initialClientAssigned`)과 비교하여 처리하는 로직으로 리팩터링
* **프로젝트 저장**
* `payload`에 `deleted: false` 기본값 추가
* `isEdited` 계산에서 `step` 비교 항목 제거
* **단계 편집 로직**
* `handleDialogConfirm` 내 `isEdit` 값을 기존 `wasEdited` 플래그와 OR 연산하여 한 번 편집된 단계는 계속 강조
* **매니저 변경 로직**
* `originalIsManager` 대신 `initialDevAssigned`/`initialClientAssigned`에서 초기 `isManager` 값을 찾아 비교
* 변경된 매니저만 `updateProjectManager` API 호출
* 기타: 불필요 파일 삭제 및 `console.log` 모두 제거
1. **프로젝트 수정**
* 필드만 변경 없이 저장 클릭 → HTTP 500 에러 발생 없이 정상 응답
2. **단계 편집**
* 단계 이름 수정 후 확인 → 해당 단계와 이전에 수정했던 단계 모두 강조 유지 확인
3. **매니저 토글**
* 개발사·고객사 직원 중 매니저 토글 후 저장 → 네트워크 탭에서 변경된 멤버만 `/updateProjectManager` 호출 확인
4. **회귀 테스트**
* …
> [refactor] 프로젝트 저장 payload 개선 및 단계·매니저 편집 로직 개선 (#417)

- src/features/project/home/components/CompanyMemberSectionContent.jsx
- src/features/project/home/components/ProjectStepManager/ProjectStepManager.jsx
- src/features/project/home/hooks/useProjectForm.js
* `save` 함수의 비동기 처리 방식을 개선하고, 자동 새로고침 시점을 조정해 모든 API 호출이 완료된 뒤 페이지가 리로드되도록 변경했습니다.
* `CompanyMemberSectionContent` 컴포넌트의 `Autocomplete`를 리팩토링하고, `memberName` 기반 검색 기능을 추가해 사용자 경험을 향상시켰습니다.
* **save 함수 비동기 로직 개선**
* `fetchAllMembers` 헬퍼 추가: `getCompanyMembersByCompanyId`를 페이지 단위로 반복 호출해 전체 직원 목록을 가져오도록 구현
* 직원 추가/삭제 로직을 `Promise` 배열로 묶고 `Promise.all`로 완전 대기
* 매니저 변경 처리 로직도 `unwrap()` 후 `Promise.all`로 병렬 대기
* `finally` 블록에 `window.location.reload()`를 이동시켜, 성공·실패 관계없이 모든 비동기 작업 완료 후 새로고침 보장
* **CompanyMemberSectionContent Autocomplete 리팩토링**
* `useDispatch`, `useParams` 제거로 불필요 의존성 정리
* `assigned` → `checkedList` 계산 로직 분리로 가독성 향상
* `onInputChange`에서 `reason === "input"` 검사 추가
* `filterOptions`를 이용해 `memberName` 기준 검색 기능 구현
* 대용량 직원 데이터(3페이지 이상)인 경우에도 `save` 호출 시 전체 목록이 잘 조회됨을 확인
* …
> [refactor] 프로젝트 저장 로직 비동기 개선 및 직원 선택 Autocomplete 리팩토링 (#417)

- src/features/project/home/components/ProjectBasicInfoSectionContent.jsx
- src/features/project/home/hooks/useProjectDetailSections.jsx
- src/features/project/home/hooks/useProjectForm.js
- src/features/project/home/pages/ProjectDetailPage.jsx
- src/features/project/slices/projectMemberSlice.js
* `useProjectForm` 훅의 상태 변경 API 호출 타이밍을 즉시 호출에서 “저장” 버튼 클릭 시점으로 이동
* 저장 중 오류 발생 시 사용자에게 `AlertMessage` 컴포넌트로 알림창을 띄우도록 추가
* `projectMemberSlice`에 매니저 권한 변경용 `updateProjectManager` Thunk와 리듀서를 구현
* **useProjectForm 훅**
* `onChange`에서 즉시 호출하던 `updateProjectStatus`를 제거하고, `save()` 내부로 모두 통합
* `save()` 함수에서 API 호출 성공 여부에 따라 로딩 화면 유지 또는 해제 로직 적용
* **ProjectDetailPage 컴포넌트**
* 저장 실패 시 `AlertMessage`를 통해 오류 알림 표시하도록 추가
* **projectMemberSlice**
* `updateProjectManager` createAsyncThunk 정의
* `.pending`/`.fulfilled`/`.rejected` extraReducers 등록
* **기능 테스트**
1. 프로젝트 상태를 변경 → 즉시 API 호출 없이 `save` 버튼 활성화
2. `save` 클릭 → 저장 로딩 화면 표시 → API 성공 후 페이지 리로드
3. API 에러 강제 발생 → 로딩 해제 후 상단 오류 알림 표시
* **매니저 권한 변경**
* 개발사/고객사 멤버 리스트에서 매니저 토글 후 저장 → 네트워크 탭에서 `updateProjectManager` 호출 확인
* #417 
* 없음.
> [refactor] 프로젝트 저장 로직 리팩터링 및 오류 알림 추가 (#417)

- src/features/project/post/components/CommentInput.jsx
- src/features/project/post/components/CommentSection.jsx
* 사용자가 작성한 댓글(리뷰)을 수정할 수 있는 기능 추가
* 기존 댓글 등록 로직에 “수정 모드” 분기 처리를 도입하고, 수정 전용 입력폼 및 버튼 UI를 구현
* `editReviewId` 존재 여부에 따라 `addReview`와 `updateReview` 액션을 분기 처리하도록 로직 추가
* 댓글 영역에서 ✏️ 버튼을 눌러 수정 모드로 전환하는 `editing` 상태 및 `EditIcon` 버튼 추가
* 수정 모드일 때 기존 텍스트 대신 `CommentInput` 컴포넌트를 렌더링하도록 조건부 렌더링 적용
* 수정 완료·취소 시 입력창 초기화 및 `onCancel` 핸들러 연결
* 수정 완료 후 `fetchReviews({ postId, page: 1 })` 호출로 최신 댓글 목록을 1페이지로 갱신
* ✏️ 버튼 클릭 → 입력폼으로 전환, 텍스트 수정 후 저장 클릭 시 API 요청 정상 호출됨
* 수정 완료 시 `setText("")` 및 `onCancel()` 호출로 입력창이 초기화되고, 댓글 목록이 1페이지로 리프레시됨
* 취소 버튼 클릭 시 기존 댓글 표시로 돌아오며 입력 내용이 남지 않음
* 댓글 등록·대댓글 기능도 의도대로 동작함을 확인
* #450 
* 없음
> [feat] 게시글의 댓글 수정 기능 추가(#450)

- src/api/company.js
- src/features/company/components/CompanyImageUploadSection.jsx
- src/features/company/pages/CompanyDetailPage.jsx
- src/features/company/pages/CompanyFormPage.jsx
- src/layouts/Sidebar.jsx
- src/utils/uploadCompanyImage.js
- 회사 로고 이미지 다운로드/업로드 버그 수정
- **회사 생성 시 이미지 업로드 수정**
- `uploadCompanyImage.js`: S3 URL 대신 파일명만 반환하도록 수정
- **회사 수정 페이지 기존 이미지 미리보기 기능 추가**
- `getCompanyImageDownloadUrl` API 함수 추가
- `logoImagePath`가 있을 때 다운로드 URL 발급 요청
- 기존 이미지 미리보기 표시 및 삭제 시 미리보기 제거
- **사이드바 회사 로고 표시 기능 구현**
- 로그인 후 회사 로고 이미지를 사이드바에 표시
- `logoImagePath`가 있으면 다운로드 URL 요청하여 이미지 표시
- **회사 상세 보기 페이지 로고 섹션 추가**
- 4번 항목으로 회사 로고 섹션 추가
- 수정 페이지와 동일한 디자인 적용 (120px 원형, gap 레이아웃)
- 이미지 다운로드 URL 요청 및 미리보기 표시
- **UI/UX 개선**
- "로고 이미지" → "회사 로고" 텍스트 통일
- 이미지 없을 때 CloudUpload 아이콘과 안내 텍스트 표시
- **회사 생성**: 이미지 업로드 후 `logoImagePath`에 파일명만 저장되는 것 확인
- **회사 수정**: 기존 이미지 미리보기 표시 및 새 이미지 선택/삭제 기능 정상 작동 확인
- **사이드바**: 로그인 후 회사 로고가 정상적으로 표시되는 것 확인  
- **상세 보기**: 회사 상세 페이지에서 로고 이미지가 올바르게 표시되는 것 확인
- **반응형**: 수정 페이지와 상세 페이지의 로고 섹션 디자인 일관성 확인
- #454
> [feat] : 회사 로고 이미지 다운로드/업로드 버그 수정

- src/features/company/pages/CompanyFormPage.jsx
- src/features/project/post/components/FileAttachmentViewer.jsx
- src/features/project/post/components/FileUploadSection.jsx
- src/features/project/post/pages/PostDetailDrawer.jsx
- src/hooks/useCompanyImageUpload.js
- src/hooks/usePostForm.js
- src/utils/downloadUtils.js
- src/utils/validateFile.js
- 게시글 수정시 이미지 업로드 기능 추가 및 작은 개선
- 게시글 수정시 이미지 업로드 기능 추가
- 게시글 생성/수정 페이지에서 파일 업로드 개수 최대 3개 제한 기능 추가
- 게시글 조회시 파일 바로 다운로드하는 로직 제거, 다운로드 버튼 클릭해야 다운로드하게 변경
- #457 
- https://github.com/Kernel360/KDEV5-MY-WORK-FE/pull/462
> [build] : 게시글 수정시 이미지 업로드 기능 추가
