scripts/generate-feature.cjs
- 도메인(feature) 디렉토리 자동 생성 스크립트(generate-feature.js)를 추가했습니다.
- scripts/generate-feature.js 스크립트 파일 추가
- 명령어 입력 시:
- src/features/{도메인이름} 폴더 자동 생성
- 내부에 pages, components 폴더 생성
- api.js, {도메인}Slice.js 기본 파일 생성
- 로컬에서 node scripts/generate-feature.js testdomain 실행
- src/features/testdomain 하위 구조가 정상 생성됨 확인
- 중복 이름 입력 시 오류 메시지 출력 확인
- 없음 ( 초기 세팅 작업)
- 없음 (자체 구현)
=> feat: 도메인 생성 자동화 스크립트 추가

src/components/CustomTable/CustomTable.jsx
- 프로젝트 전반에 사용 가능한 `CustomTable` 공통 컴포넌트를 구현했습니다.
- 컬럼 기반 구성으로 다양한 타입(checkbox, text, link, status 등)을 지원하며,
- 정렬, 필터, 검색, 페이지네이션 기능이 포함된 고도화된 테이블입니다.
---
- CustomTable 컴포넌트 추가 (`src/components/common/CustomTable.jsx`)
- columns config 기반 렌더링 구조 설계
- type별 렌더링 로직 (`renderCellContent`) 구현
- checkbox, avatar, link, number, boolean, tag, action 등
- 정렬(sortable) 기능 구현 (정렬 상태 시 sort 아이콘 유지 노출)
- 필터(filter) 기능 구현 (status 타입 자동 추출 기반)
- 검색창 노출 옵션 추가 (search 옵션 존재 시 표시)
- row 클릭 시 상세 이동 / 내부 클릭 방지 처리
- 반응형 가로/세로 스크롤 처리 및 콘텐츠 영역 내 스크롤 고정
---
---
- ProjectPage 등에서 실제 데이터 연동하여 테스트 완료
- 모든 타입별 렌더링 확인 및 필터/정렬/검색 기능 정상 동작 확인
- 브라우저 리사이즈 및 모바일 화면에서도 레이아웃 무너짐 없음
---
- `- #9 ` - CustomTable 공통 컴포넌트 개발 및 기능 고도화
- `- #10 ` - ProjectPage - 목록 조회 화면 개발 및 테이블 연동
---
- [MUI Table …
=> feat: 커스텀 테이블 컴포넌트 개발 및 정렬/필터/검색 기능 추가

package-lock.json, package.json, src/api/api.js, src/api/project.js, src/features/project/projectSlice.js, src/store/store.js, vite.config.js
- 프로젝트 CRUD 기능을 위한 초기 세팅 완료했습니다.
- API 요청, Redux 상태 관리, 전역 Store 구성을 위한 공통 구조를 설계했습니다.
- 'src/api/api.js': axios 인스턴스 생성
- 'src/api/project.js': 프로젝트 관련 API 함수 정의
- 'src/api/store.js': Redux Toolkit 기반 전역 스토어 설정
- 'src/feature/project/projectSlice.js': 프로젝트 관련 Redux 상태 구성
- json-server와 연동하여 프로젝트 목록 조회 및 상태 저장 정상 작동 확인
- fetchProjects -> store.data 반영 OK
- #7 
- [Redux Toolkit createAsyncThunk] (https://redux-toolkit.js.org/api/createAsyncThunk)
=> feat: 프로젝트 API, Redux Slice, 전역 Store 및 axios 인스턴스 세팅 (#7)

src/components/common/customButton/CustomButton.jsx, src/components/layouts/pageHeader/PageHeader.jsx, src/components/table/CustomTable.jsx, src/features/project/components/ProjectTable.jsx, src/features/project/pages/ProjectPage.jsx
=> 프로젝트 페이지 UI를 개별 컴포넌트로 분리

.github/workflows/deploy.yml
=> dev 브랜치 푸시 시 스테이징 자동 배포 워크플로우 추가(#20)

.github/workflows/deploy.yml
=> refactor: dev 브랜치 푸시 시 스테이징 자동 배포 워크플로우 수정(#20)

src/api/company.js, src/api/member.js, src/api/project.js, src/features/company/companySlice.js, src/features/member/memberSlice.js, src/features/project/projectSlice.js, src/store/store.js
=> 프로젝트·회사·멤버 API/Redux 로직 통합 및 스토어 등록

src/components/common/confirmDialog/ConfirmDialog.jsx, src/components/common/sectionTable/SectionTable.jsx, src/components/common/sectionTable/SectionTable.styles.js, src/components/common/summaryCard/SummaryCard.Styles.js, src/components/common/summaryCard/SummaryCard.jsx, src/components/layouts/tabsWithContent/TabsWithContent.jsx, src/components/table/CustomTable.jsx
=> 공통 컴포넌트(CustomTable, ConfirmDialog, SectionTable, SummaryCard, TabsWithContent) 추가

src/features/project/components/ProjectTable.jsx
=> 프로젝트 리스트 표시용 ProjectTable 컴포넌트 추가

src/api/member.js, src/features/member/components/MemberTable.jsx, src/features/member/memberSlice.js, src/features/member/pages/MemberPage.jsx, src/features/project/components/ProjectTable.jsx, src/routes/MainRoutes.jsx
-회원 목록 조회 페이지
- 전달받은 정보로 회원 목록을 노출한다
#39
=> [feat] 회원 목록 조회 페이지

src/api/member.js, src/api/post.js, src/api/project.js, src/api/projectCheckList.js, src/api/projectMember.js, src/api/projectStep.js, src/api/review.js, src/components/common/customTable/CustomTable.jsx, src/features/project/components/ProjectTable.jsx, src/features/project/projectSlice.js
=> refactor: CustomTable 검색·필터 조건 분리 및 정렬 기능 개선(#52)

src/api/projectStep.js, src/components/common/customTable/CustomTable.jsx, src/features/project/components/ProjectTable.jsx, src/features/project/projectSlice.js
=> fix: merge conflict 해결 및 충돌난 코드 병합(#49)

src/components/common/customTable/CustomTable.jsx, src/features/member/components/MemberTable.jsx
=> [fix]CustomTable 검색 로직 개선 – avatar 객체의 name 속성으로 검색 지원(#63)

src/features/member/pages/MemberDetailPage.jsx, src/features/member/pages/MemberPage.jsx, src/routes/MainRoutes.jsx
멤버 상세 페이지 
멤버 상세 정보를 보여주는 페이지
화면테스트
#60
필드추가
생성일 , 권한, 최근수정일 , 회사 전화번호
삭제 와 수정 버튼 api 연결
=> feat: 멤버 상세 페이지

src/api/api.js, src/routes/MainRoutes.jsx
=> [fix]로그인 미인증 사용자의 비인가 경로 접근 시 로그인 페이지로 리다이렉트(#78)

src/features/member/components/MemberTable.jsx
- 회원목록 조회 조건추가
-회사 필드 추가 검색조건에 추가  
- 상태 필드 제거
#84
=> [fix] 회원목록 조회 조건추가 #84

src/components/common/sectionTable/SectionTable.jsx, src/features/project/post/components/PostTable.jsx
=> [refactor]섹션 테이블에 type 파라미터 기반 노출 기능 추가 및 PostTable 렌더링 개선(#83)

constants/navItems.js, src/features/company/components/ClientCompanyForm.jsx, src/features/company/components/ClientCompanyTable.jsx, src/features/company/pages/ClientCompanyFormPage.jsx, src/features/company/pages/ClientCompanyPage.jsx, src/routes/MainRoutes.jsx
- 고객사 페이지 페이지 작업
- 고객사 페이지 페이지 작업
- #70
=> [feat] 고객사 페이지 작업

src/features/member/pages/MemberDetailPage.jsx, src/utils/roleUtils.js
- 노출되는 상세값 추가 
- 노출되는 상세값 추가 
프로젝트 리스트를 추가  회사 정보를 추가 회원 정보 생성일 수정일 추가
#66
=> fix:노출되는 상세값 추가 

src/components/common/sectionTable/SectionTable.jsx, src/features/project/checklist/pages/ProgressOverview.jsx, src/features/project/pages/ProjectDetailPage.jsx, src/features/project/post/components/PostTable.jsx
=> [feat]진척도 관리 화면 컴포넌트 추가 및 상태별 체크리스트 카드 렌더링 구현(#87)

src/features/company/companySlice.js, src/features/member/components/MemberForm.jsx, src/features/member/pages/MemberFormPage.jsx
=> [fix]멤버 생성 폼에서 회사 목록 id/name 매핑 및 셀렉트 렌더링 수정(#92)

src/features/project/components/ProjectTable.jsx, src/utils/statusUtils.js
=> [fix]프로젝트 목록 테이블 statusMap 키·색상 매핑 수정(#97)

.env, src/api/api.js, src/features/project/components/ProjectTable.jsx, src/utils/statusUtils.js
=> [feat]개발자 직원 설정 기능 초기 구현(#101)

src/features/member/components/MemberForm.jsx
=> [refactor]MemberForm 디자인 개선(#104)

src/components/common/customTable/CustomTable.jsx, src/features/company/components/ClientCompanyForm.jsx, src/features/company/components/ClientCompanyTable.jsx, src/features/company/components/DevCompanyForm.jsx, src/features/company/components/DevCompanyTable.jsx, src/features/member/components/MemberForm.jsx, src/features/project/components/ProjectForm.jsx, src/features/project/components/ProjectTable.jsx, src/features/project/pages/ProjectPage.jsx
=> Feature/#107CustomTable: 회사 컬럼 ID→이름 매핑 및 렌더러 개선(#107)

src/api/project.js, src/components/common/customTable/CustomTable.jsx, src/features/company/components/ClientCompanyForm.jsx, src/features/company/components/ClientCompanyTable.jsx, src/features/company/components/DevCompanyForm.jsx, src/features/company/components/DevCompanyTable.jsx, src/features/member/components/MemberForm.jsx, src/features/project/components/ProjectForm.jsx, src/features/project/components/ProjectTable.jsx, src/features/project/management/components/ClientMemberManager/ClientMemberList.jsx, src/features/project/management/components/ClientMemberManager/ClientMemberSelector.jsx, src/features/project/management/components/DevMemberManager/DevMemberList.jsx, src/features/project/management/hooks/useProjectSections.jsx, src/features/project/pages/ProjectDetailPage.jsx, src/features/project/pages/ProjectPage.jsx, src/features/project/projectSlice.js
=> [feat]고객사 직원 관리 기능 구현: ClientMemberSelector & ClientMemberList 추가(#111)

src/api/post.js, src/components/common/sectionTable/SectionTable.jsx, src/features/project/post/components/PostDetailDrawer.jsx, src/features/project/post/components/PostTable.jsx, src/features/project/post/components/createPostDrawer.jsx, src/features/project/post/postSlice.js
=> feat: CreatePostDrawer에 게시글 생성 로직 구현(#124)

src/features/company/components/ClientCompanyTable.jsx, src/features/company/pages/ClientCompanyDetailPage.jsx, src/routes/MainRoutes.jsx
=> [fix]고객사 리스트에서 상세 페이지로 이동 기능 수정(#135)

src/features/project/post/components/CommentSection.jsx, src/features/project/post/components/PostDetailDrawer.jsx, src/features/project/post/reviewSlice.js, src/store/store.js
=> [feat]구현된 댓글/대댓글 기능 및 “더보기” 페이징 버튼 통합(#133)

src/features/project/components/ProjectTable.jsx, src/features/project/projectSlice.js
- 프로젝트 페이징 수정 #145
- 프로젝트 페이징 수정
검색시 페이징 변경되지 않던점을 수정 
- 화면테스트
#145
=> 프로젝트 페이징 수정

constants/navItems.js, src/features/project/components/ProjectTable.jsx, src/features/project/pages/ProjectPage.jsx, src/layouts/Sidebar.jsx
- 관리자 dev와 client 일반사용자 권한에 따른 페이지노출
dev 는 프로젝관리 노출 단 상세 진입시 알럿노출( 관리자에게 문의해주세요.)
client 프로젝관리 및 프로젝트 목록 미노출
systemadmin 모든것 열람가능
- 화면테스트
#151
=> feat : 관리자 dev와 client 일반사용자도 권한에 따른 페이지 노출

src/features/member/pages/MemberDetailPage.jsx, src/routes/MainRoutes.jsx
=> [fix] 멤버 관리 수정 기능 수정 (#152)

src/api/company.js, src/features/company/companySlice.js, src/features/company/pages/ClientCompanyFormPage.jsx, src/features/company/pages/DevCompanyFormPage.jsx
개발사 고객사 수정 API 수정
- 백엔드 API 기준으로 데이터 전달변경
기존 path : companyId   , body  : 상세정보
변경 body  : companyId,상세정보
UUID 형식에 맞춰서 companyId 값 전달되도록 수정.
화면에서 직접 테스트 데이터를 통해서 수정.
#160
=> [fix] 개발사 고객사 수정 API 수정

src/api/member.js, src/features/member/components/MemberForm.jsx, src/features/member/memberSlice.js, src/features/member/pages/MemberFormPage.jsx
=> [fix]멤버 수정 전반적인 오류 수정(#152)

src/api/member.js, src/features/member/components/MemberForm.jsx, src/features/member/memberSlice.js, src/features/member/pages/MemberFormPage.jsx
=> [fix]멤버 수정 전반적인 오류 수정(#72)

src/api/api.js, src/features/auth/pages/LoginPage.jsx, src/features/member/memberSlice.js, src/features/project/post/components/PostTable.jsx
=> [feat]로그인 로직 안정화 및 로그인 페이지 리다이렉트 처리(#173)

src/components/common/sectionTable/SectionTable.jsx, src/features/project/post/components/CommentSection.jsx
=> [fix] SectionTable import 오타 수정(#72)

src/api/member.js, src/components/common/sectionTable/SectionTable.jsx, src/features/auth/pages/LoginPage.jsx, src/features/member/memberSlice.js, src/features/member/pages/MemberPage.jsx, src/features/project/pages/NoProjectsPage.jsx, src/features/project/post/components/CommentSection.jsx, src/layouts/Sidebar.jsx, src/routes/MainRoutes.jsx
=> [refactor]프로젝트 조회 실패 시 /no-projects로 fallback 통일(#172)

src/components/common/customTable/CustomTable.jsx
=> [fix]로그인 시 로컬스토리지 초기화로 이전 세션 정보 제거(#181)

src/components/common/customTable/CustomTable.jsx, src/features/auth/pages/LoginPage.jsx
=> [fix]로그인 시 로컬스토리지 초기화로 이전 세션 정보 제거(#181) 

src/components/common/customTable/CustomTable.jsx, src/components/common/sectionTable/SectionTable.jsx, src/features/company/components/ClientCompanyTable.jsx, src/features/company/components/DevCompanyTable.jsx, src/features/project/post/components/PostDetailDrawer.jsx, src/features/project/post/components/PostTable.jsx
=> [feat]회사명 아바타 렌더링 및 '주식회사' 접두어 제거 적용(#180)

src/api/project.js, src/features/company/components/ClientCompanyForm.jsx, src/features/company/components/DevCompanyForm.jsx, src/features/member/components/MemberForm.jsx, src/features/member/pages/MemberFormPage.jsx, src/features/project/components/ProjectForm.jsx, src/features/project/pages/ProjectFormPage.jsx, src/features/project/projectSlice.js
=> [fix] 멤버/프로젝트 수정 오류 개선(#186)

src/features/project/pages/ProjectPage.jsx
=> [feat]SYSTEM_ADMIN만 프로젝트 생성 버튼 노출(#188)

constants/navItems.js, src/layouts/Sidebar.jsx
=> [refactor]Sidebar 메뉴 구조 개선 및 children 메뉴 항상 노출되도록 수정(#190)

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
* 프로젝트 이슈 등록 시 사용할 이슈 템플릿을 추가했습니다.
* 버그 리포트용 / 기능 개발용 두 가지 템플릿을 작성했습니다.
* `.github/ISSUE_TEMPLATE` 폴더 생성
* `bug-report.yml` (버그 리포트용) 템플릿 추가
* `feature-request.yml` (기능 개발용) 템플릿 추가
* 로컬에서 템플릿 작성 완료
* dev 브랜치에 반영 후 이슈 생성 시 정상 동작 확인 예정
* 없음
* [[GitHub 이슈 템플릿 공식 문서](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-issue-and-pull-request-templates)](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-issue-and-pull-request-templates)
=> [chore] 이슈 템플릿 작성 및 등록(#197)

src/components/common/customTable/CustomTable.jsx, src/features/project/components/ProjectTable.jsx
- 공통 테이블 컴포넌트인 `CustomTable`에 수정/삭제 버튼을 추가하였고,  
프로젝트 테이블에서 각 버튼 클릭 시 동작할 수 있도록 `onEdit`, `onDelete` 핸들러를 연동하였습니다.
- CustomTable 컴포넌트에 액션 버튼 컬럼 추가 (수정/삭제 버튼)
- CustomTable props에 `onEdit`, `onDelete` 콜백 함수 추가
- 프로젝트 테이블에서 각 행에 맞는 수정/삭제 기능 구현 및 연결
- 삭제 클릭 시 확인 모달 연동 (선택 시 실제 삭제 함수 실행)
- 로컬에서 프로젝트 리스트를 불러와 각 행에 대해 수정/삭제 버튼 정상 동작 확인
- 삭제 버튼 클릭 시 모달이 뜨고, 확인을 누르면 실제 삭제 동작 확인
- 수정 버튼 클릭 시 해당 로직 진입 
- #204 
- [MUI Table Actions 예제](https://mui.com/material-ui/react-table/#column-grouping)
=> [refactor]커스텀 테이블에 수정/삭제 버튼 추가 및 프로젝트 테이블에 onEdit/onDelete 기능 연결(#204)

.env, .env.development, .env.production
- Vite 개발/운영 환경 분리 및 API 주소 설정
- `.env.development` / `.env.production` 파일 분리 및 API 주소 설정
- Axios 인스턴스에 `import.meta.env.VITE_API_BASE_URL` 적용
- #206 
- [Vite 공식 문서 - 환경 변수](https://vitejs.dev/guide/env-and-mode.html)
=> [feat]Vite 환경 분리 및 운영 서버 API 주소 설정(#206)

src/api/api.js, src/components/common/errorPage/ForbiddenPage.jsx, src/components/common/errorPage/NotFoundPage.jsx, src/components/common/protectedRoute/ProtectedRoute.jsx, src/features/project/pages/ProjectDetailPage.jsx, src/routes/MainRoutes.jsx
- 접근권한 페이지 404,403 공통페이지 설정 추가
- 프로젝트 접근권한 공통 페이지 작업
-  유저권한으로 project/new  접근 ( 권한 오류 403)
-  아무권한으로 이상한 uri 작성 후 진입 ( 404 ) 
- #213
=> 접근권한 페이지 404,403 공통페이지 설정 추가

src/features/company/pages/CompanyPage.jsx, src/features/member/pages/MemberPage.jsx, src/features/project/home/components/ProjectTable.jsx, src/features/project/home/pages/ProjectPage.jsx
=> [refactor] 목록 테이블 UI 정리: 생성 버튼 및 상태 컬럼 제거(#241)

src/features/project/approval/components/ProjectApprovalDetailDrawer.jsx, src/features/project/approval/pages/ProjectApprovalsPage.jsx
=> [feat] ProjectApprovalDetailDrawer 컴포넌트 분리 및 상세 조회 API 연동 (#249)

src/components/common/customTable/CustomTable.jsx, src/features/project/approval/components/ProjectApprovalDetailDrawer.jsx, src/features/project/approval/pages/ProjectApprovalsPage.jsx, src/features/project/home/components/ProjectCardList.jsx, src/features/project/home/components/ProjectTable.jsx, src/features/project/home/pages/ProjectPage.jsx
=> [feat]결재관리 카드 UI 개선 및 작성자/단계 정보 표시 기능 추가 (#249)

src/api/project.js, src/features/project/home/pages/ProjectPage.jsx, src/features/project/slices/projectSlice.js
-내 프로젝트 조회 API 수정
- api 수정 내프로젝트만 조회
- 내프로젝트만 조회시 total값 나오지않아 프론트에서 계산
- 화면 테스트
#264
=> [fix] 내 프로젝트 조회 API 수정 #264

src/features/dashboard/components/ProjectAmountChart.jsx, src/features/project/approval/components/ApprovalActionInput.jsx, src/features/project/approval/components/ApprovalDetailContent.jsx, src/features/project/approval/components/ApprovalDetailHeader.jsx, src/features/project/approval/components/ApprovalHistoryList.jsx, src/features/project/approval/components/ProjectApprovalDetailDrawer.jsx
=> [refactor] 결재 상세 Drawer 컴포넌트 분리 및 결재 히스토리 UI 추가(#269)

src/features/project/approval/components/ApprovalActionInput.jsx, src/features/project/approval/components/ApprovalDetailHeader.jsx, src/features/project/approval/components/ApprovalHistoryList.jsx, src/features/project/approval/components/CreateCheckListDrawer.jsx, src/features/project/approval/components/ProjectApprovalDetailDrawer.jsx, src/features/project/approval/pages/ProjectApprovalsPage.jsx
=> [feat] 체크리스트 항목 생성용 CreateCheckListDrawer 컴포넌트 구현(#273)

src/features/project/approval/components/ApprovalActionInput.jsx, src/features/project/approval/components/ApprovalDetailHeader.jsx, src/features/project/approval/components/ApprovalHistoryList.jsx, src/features/project/approval/components/CreateCheckListDrawer.jsx, src/features/project/approval/components/ProjectApprovalDetailDrawer.jsx, src/features/project/approval/pages/ProjectApprovalsPage.jsx
=> [feat] 체크리스트 생성 드로어 및 결재 항목 생성 기능 구현 (#273)

src/features/dashboard/components/ProjectAmountChart.jsx
-fix : 대시보드 차트 x축 순서 변경 #277
- 대시보드 x 축  순서 변경
- #277
=> fix : 대시보드 차트 x축 순서 변경 #277

src/api/checklistHistory.js, src/features/project/approval/checklistHistorySlice.jsx, src/features/project/approval/components/ProjectApprovalDetailDrawer.jsx, src/store/store.js
=> [feat] 결재 상세 Drawer에 체크리스트 이력 API 연동(#269)

src/features/notifications/components/NotificationsDrawer.jsx, src/layouts/Sidebar.jsx
=> [feat] 알림 드로어 UI 리디자인 및 읽지 않은 알림 표시 개선(#267)

src/features/project/approval/pages/ProjectApprovalsPage.jsx, src/features/project/home/pages/ProjectLayout.jsx
- 체크리스트 생성 버튼 및 명칭변경
- 체크리스트 페이지 버튼 위치 수정
- 체크리스트 탭 결재 관리 -> 체크리스트  로 수정
-
#286
=> [chore] 체크리스트 생성 버튼 및 명칭변경 #286

src/features/dashboard/pages/DashboardPage.jsx
=> [refactor] 대시보드 페이지 UI 개선 및 테마 기반 색상 적용(#256)

src/api/dashboard.js
-  대시보드 summary 리팩토링 영향 api 주소 변경 #295
- api 호출 주소 변경 totalSummery -> total-summary
-화면 테스트 데이터 노출 확인.
#295
=> [chore] 대시보드 summary 리팩토링 영향 api 주소 변경 #295

index.html, src/features/auth/pages/LoginPage.jsx
=> [refactor] 로그인 화면 UI 및 index.html 타이틀 수정 (#241)

src/features/project/approval/pages/ProjectApprovalsPage.jsx, src/features/project/post/components/CreatePostDrawer.jsx
=> [refactor] 멘트 수정(#241)

src/features/member/pages/MemberDetailPage.jsx, src/features/member/pages/MemberFormPage.jsx, src/features/project/slices/projectMemberSlice.js, src/features/project/slices/projectSlice.js
=> [refactor] 멤버 -> 회원 용어 통일(#241)

src/features/company/components/CompanyForm.jsx
- 업체 생성시에 누락된 필드 추가 # 327
- 업체 생성시에 누락된 필드 추가   고객사 , 개발사
- 화면에서 테스트
#327
=> fix : 업체 생성시에 누락된 필드 추가 # 327

src/components/common/sectionTable/SectionTable.jsx, src/features/project/post/pages/ProjectPostsPage.jsx
* 테이블 UI의 시각적 완성도를 높이고, 상태 라벨 문구를 사용자에게 더 명확하게 전달하도록 수정
---
* 테이블 행(`TableRow`)에 배경색과 외곽선 스타일 추가
* 테이블 셀(`TableCell`)에 상하 테두리 스타일 적용
* 상태 라벨 문구 변경
* `대기` → `답변 대기`
* `완료` → `답변 완료`
---
---
* 디자인 상 맞지 않던 좌우 테두리가 제거되고 상하 테두리만 남아 시각적 정렬이 개선됨
* 라벨 문구 변경 후 사용자 혼동 요소 없이 정상 표기됨 확인
* 반응형 화면에서도 레이아웃 이상 없음
---
* `- #358`
---
* 없음
=> [refactor] 테이블 스타일 및 상태 라벨 문구 수정 (#358)

src/components/common/alertMessage/AlertMessage.jsx, src/features/notifications/components/NotificationsDrawer.jsx, src/features/notifications/notificationSlice.js, src/features/project/post/postSlice.js, src/layouts/MainLayout.jsx
* 알림 Drawer에서 삭제된 게시글 클릭 시 예외를 방지하고 사용자에게 알림을 표시하도록 처리했습니다.
* `AlertMessage` 컴포넌트를 Drawer 외부(MainLayout)로 분리하여 전역에서 재사용 가능하도록 리팩터링했습니다.
---
* 삭제된 게시글(`ERROR_POST09`) 접근 시 페이지 이동 차단 및 경고 메시지 표시
* 게시글 조회 실패 시 에러 메시지 알림 출력
* `AlertMessage`를 `MainLayout`에서 렌더링하도록 변경
* `NotificationsDrawer`는 알림 상태만 외부로 전달하도록 구조 변경
* Drawer 외부 영역 클릭 시 Drawer 닫히도록 백드롭 처리 추가
* `AlertMessage` 내 `container={() => document.body}` 제거 (불필요)
---
---
* 삭제된 게시글 클릭 시 `"삭제된 게시글입니다."` 메시지가 정상적으로 출력됨
* Drawer 내부와 외부 클릭 동작 모두 예상대로 작동
* AlertMessage가 상위(MainLayout)에서 렌더링되어 다른 화면에서도 표시 문제 없음
* 읽음 처리 및 unread 카운트 정상 반영됨
---
* `- #364`
---
* 없음
=> [refactor] 알림 Drawer 내 게시글 접근 예외 처리 및 AlertMessage 전역화 (#364)

.github/workflows/deploy.yml, src/components/common/alertMessage/AlertMessage.jsx, src/features/notifications/components/NotificationsDrawer.jsx, src/features/notifications/notificationSlice.js, src/features/project/post/postSlice.js, src/layouts/MainLayout.jsx
=> [build] CI/CD 대상 브랜치를 dev → main 으로 변경(#366)

src/features/company/components/CompanyTable.jsx, src/features/company/pages/CompanyPage.jsx, src/features/member/components/MemberTable.jsx, src/features/member/pages/MemberPage.jsx, src/features/project/post/pages/CreatePostDrawer.jsx, src/hooks/usePostForm.js
=> [fix] 게시글 작성 Drawer가 닫히지 않는 버그 수정

src/features/project/home/components/CompanyMemberSelector.jsx, src/features/project/home/components/ProjectTable.jsx
=> [feat] 프로젝트 검색 시 searchKey에 따라 keywordType 분기 처리(#385)

src/api/company.js, src/features/company/components/CompanyForm.jsx, src/features/company/components/CompanyImageUploadSection.jsx, src/features/company/pages/CompanyFormPage.jsx, src/hooks/useCompanyImageUpload.js, src/layouts/Sidebar.jsx, src/utils/uploadCompanyImage.js
- 업체 등록/수정 시 회사 로고 이미지 등록 기능 추가
- S3 Direct Upload 방식을 통한 안전하고 효율적인 이미지 업로드 시스템 구현
- 이미지 업로드 UI 컴포넌트 구현 (CompanyImageUploadSection.jsx)
- 이미지 업로드 커스텀 훅 구현 (useCompanyImageUpload.js)
- 이미지 업로드 API 연동
- 파일 검증 시스템 (validateFile.js)
- #379
=> feat : 업체 등록시 회사 이미지 등록하게 추가

src/features/project/home/pages/ProjectLayout.jsx
=> [chore] '체크리스트' -> '체크리스트 관리'로 변경(#358)

src/features/project/home/pages/ProjectLayout.jsx
=> [chore] 메뉴 이름을 '게시판'과 '체크리스트'로 변경(#358)

src/api/projectMember.js, src/features/project/home/components/CompanyMemberList.jsx, src/features/project/home/components/CompanyMemberSelector.jsx
-  백엔드 api 호출 주소변경으로 인한 매니저 할당 api수정
-  백엔드 api 호출 주소변경으로 인한 매니저 할당 api수정
화면테스트
#400
=> fix : 백엔드 api 호출 주소변경으로 인한 매니저 할당 api수정

src/features/project/post/pages/CreatePostDrawer.jsx
=>  [build] main에 반영

src/features/member/pages/MemberDetailPage.jsx
=> [refactor] 회원 상세에 삭제 버튼 제거(#358)

src/features/company/pages/CompanyFormPage.jsx, src/hooks/useCompanyImageUpload.js, src/utils/uploadCompanyImage.js
-  회사 수정 페이지에서 이미지 업로드 버그 수정
- 예:
- #426 
- 에:
=> [feat] : 회사 수정 페이지에서 이미지 업로드 버그 수정

src/api/api.js, src/layouts/MainLayout.jsx
- 403 공통 페이지 수정 알럿으로 대체 #434
- 403 공통 페이지 변경 알럿으로
-화면 테스트 
#434
=> chore : 403 공통 페이지 수정 알럿으로 대체 #434

README.md, src/features/project/post/components/CommentInput.jsx, src/features/project/post/components/CommentSection.jsx, src/features/project/post/components/PostDetailTopSection.jsx, src/features/project/post/pages/PostDetailDrawer.jsx
=> [chore] readme 작성 main에 반영

src/features/project/home/pages/ProjectDetailPage.jsx
=> [fix] 프로젝트 상세페이지 편집 버튼 권한 범위 확장 (개발사·고객사 관리자 추가)(#456)

README.md, src/api/company.js, src/features/company/components/CompanyImageUploadSection.jsx, src/features/company/pages/CompanyDetailPage.jsx, src/features/company/pages/CompanyFormPage.jsx, src/features/project/home/pages/ProjectDetailPage.jsx, src/features/project/post/components/CommentInput.jsx, src/features/project/post/components/CommentSection.jsx, src/features/project/post/components/PostDetailTopSection.jsx, src/features/project/post/pages/PostDetailDrawer.jsx, src/layouts/Sidebar.jsx, src/utils/uploadCompanyImage.js
=> [build] 프로젝트 상세페이지 편집 버튼 권한 범위 확장 main에 반영

src/features/company/components/CompanyForm.jsx, src/features/company/pages/CompanyFormPage.jsx, src/features/member/components/MemberForm.jsx, src/features/project/home/components/ProjectBasicInfoSectionContent.jsx, src/features/project/home/components/ProjectForm.jsx, src/features/project/home/hooks/useProjectDetailSections.jsx, src/features/project/home/hooks/useProjectForm.js, src/features/project/home/pages/ProjectFormPage.jsx
- 벨리데이션 체크 #460
-  회원,프로젝트,업체 생성시 벨리데이션 체크
-화면테스트
#460
=> feat: 프로젝트,회원,업체 생성,수정 벨리데이션 체크 #460

src/components/common/customTable/CustomTable.jsx
- 회원삭제 버튼 권한 추가 #464
- 회원삭제 버튼 권한 추가 
- AS-IS : 시스템 어드민
- TO-BE: 시스템 어드민, 고객사 어드민, 개발사 어드민
- 화면 테스트
#464
=> feat: 회원삭제 버튼 권한 추가 #464

src/constants/navItems.js, src/features/project/home/components/ProjectBasicInfoSectionContent.jsx
- 로그기록 권한 수정 #466
- 권한수정 
로그기록은 시스템 어드민 전용이라 권한 제거
-화면테스트
#466
=> fix : 로그기록 권한 수정 #466
